### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by ai** [sylvainpolletvillard/postcss-grid-kiss#6]
I think you wrote really great tool. And a lot of stars show that many people agree with me.

But for my experience, good tools = good code + good marketing :).

We need to promote you :). I think current plan could be:

1. Reddit post (I could do it tomorrow).
2. IE support.
3. CSS Tricks article.

CSS Trick is very open for new ideas. And they have no good tools article for a time. So they could accept. Just write them and ask it (explain why it is important and how people like your project, mention that your already have React port).

CSS Tricks article was a first booster for Autoprefixer promotion :).

I think your project is in very good time for promotion, because many people really want to use Grids. But they need a 3 months for even Chrome support.

You have a pure-CSS fallback and awesome syntax. It you will promote your project in December you could become much more popular. In the end of December will be a dead season, so I highly recommend to post CSS Tricks article in the beginning of December. This could be time sensitive, because right now people thought that “Chrome support will in next year”.

**Comment by sylvainpolletvillard** [comment]
Yes, marketing ! I don't have a lot of experience in promoting OS projects, so your advices are welcome.

Okay for a post on Reddit, go on :+1: And I'll write to CSS Tricks team.

You may have noticed that even with all these stars I have very few downloads. I wish more people could test the plugin, because I know my unit tests and manual testing on the playground are not enough to cover all the possible issues of such layouts. Grid-kiss is still a newborn... a beloved one :wink:

Thanks for your support by the way ! We should chat on grid-kiss Gitter channel about the organization of the promotion

**Comment by sylvainpolletvillard** [comment]
2. IE 9/10/11 support ✅

**Comment by ai** [comment]
@sylvainpolletvillard reddit post is done too https://www.reddit.com/r/webdev/comments/5edn7z/pure_css_polyfill_for_grid_layout_with_better/

Vote and keep it to bookmarks to answer for questions

**Comment by ai** [comment]
@sylvainpolletvillard could you write tweet that you support all browsers? With screenshot of syntax (to remind what is grid kiss). I will RT it by PostCSS account.
